# Local Database Connection
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

#spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db
#spring.datasource.username=postgres
#spring.datasource.password=otyultebrohout99

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.open-in-view=false
#spring.thymeleaf.cache=false

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.timeout=30m


# For production (add later for Railway)
# spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
#spring.thymeleaf.cache=false